config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    authenticated :user do
      root 'accounts#detail', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get 'accounts/detail', as: 'user_root'
  get 'accounts/:id', to: 'transactions#detail'
  
  resources :accounts, shallow: true do
    resources :transactions, shallow: true
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  has_many :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operation.rb
class Operation < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :operation
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def detail
    @user = User.find(current_user.id)
    @accounts = @user.accounts
#    def index
#      @accounts = Account.all
#
#      render 'new'
#    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

    def after_sign_up_path_for(resource)
      @account = Account.new(user_id: resource.id)
      @account.save
      signed_in_root_path(resource)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def detail
    @account = Account.find(params[:id])
    @transactions = @account.transactions

    def new
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/detail.html.erb
<div class="container">
  <nav class="navbar navbar-default">
   <div class="container-fluid">
     <div class="navbar-header">
       <a class="navbar-brand">Simple Online Bank</a>
     </div><!-- /.navbar-header -->

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	  <li><p class="navbar-text">Здравствуйте, <%= current_user.first_name %> <%= current_user.last_name %></p></li>
	  <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
	<% else %>
	  <li><%= link_to 'Войти', new_user_session_path %></li>
          <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>  
	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!--/.container-fluid -->
  </nav>


  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.number %></td>
      <td><%= account.balance %></td>
      <td><%= link_to 'Back', account_path(account) %></td>
    </tr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleOnlineBank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/detail.html.erb
<div class="container">
  <nav class="navbar navbar-default">
   <div class="container-fluid">
     <div class="navbar-header">
       <%= link_to 'Simple Online Bank', unauthenticated_root_path, class: 'navbar-brand' %>
     </div><!-- /.navbar-header -->

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	  <li><p class="navbar-text">Здравствуйте, <%= current_user.first_name %> <%= current_user.last_name %></p></li>
	  <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
	<% else %>
	  <li><%= link_to 'Войти', new_user_session_path %></li>
          <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>  
	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!--/.container-fluid -->
  </nav>

  <td><%= link_to 'Back', new_account_transaction_path(@account) %></td>
</div>

app/views/transactions/new.html.erb
<div class="container">
  <nav class="navbar navbar-default">
   <div class="container-fluid">
     <div class="navbar-header">
       <%= link_to 'Simple Online Bank', unauthenticated_root_path, class: 'navbar-brand' %>
     </div><!-- /.navbar-header -->

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	  <li><p class="navbar-text">Здравствуйте, <%= current_user.first_name %> <%= current_user.last_name %></p></li>
	  <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
	<% else %>
	  <li><%= link_to 'Войти', new_user_session_path %></li>
          <li><%= link_to 'Зарегистрироваться', new_user_registration_path %></li>  
	<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
   </div><!--/.container-fluid -->
  </nav>
</div>